### ISSUE TITLE
inkgd not in asset library

### ISSUE THREAD

**Issue by RobertWalter83** [ephread/inkgd#1]
**Describe the bug**
I wanted to try out this plugin, but cannot find it in the asset library

**To Reproduce**
I searched for inkgd as well as looking for it in the alphabetically ordered list, no inkgd.
![image](https://user-images.githubusercontent.com/5462981/58159331-9212b800-7c7c-11e9-935a-764d8af61a41.png)

**Environment:**
 - OS: Windows 10
 - Inklecate version: 0.8.2
 - _inkjs_ version: not yet installed
- Godot: 3.1.1.stable.official

**Comment by ephread** [comment]
Hey @RobertWalter83, it was only accepted a few minutes/hours ago (yay \o/): https://godotengine.org/asset-library/asset/349

Might be a caching issue on their end, I'll watch this closely, but you may want to try again in a few hours.

**Comment by RobertWalter83** [comment]
Wow, didn't know it's that fresh! Congrats!

**Comment by ephread** [comment]
Thank you! Yeah, it's super new, I released it two days ago!

Upon further investigation, the asset is tagged as _Testing_, not as _Community_ which is most likely the reason why it doesn't appear in the editor. It might have defaulted to "Testing" because it's tagged with a version below 1.0 though, so I'll have to ask whether it's going to be a problem or not on the Discord.

In the meantime (I should probably put that in the README), you're probably better off downloading the [release](https://github.com/ephread/inkgd/archive/0.1.1.zip) and importing it through the AssetLib tab.

Don't hesitate to open up issues if there's something missing/unclear in the doc or if you encounter a nasty bug and thanks for your support!

**Comment by Calinou** [comment]
After approving the asset, I forgot to change the support level from *Testing* to *Community* (*Testing* being the default level when an asset is newly-approved). Sorry for the inconvenience.

**Comment by ephread** [comment]
@Calinou all good, thanks for the swift response!
