### ISSUE TITLE
Update INK_VERSION_CURRENT to 20

### ISSUE THREAD

**Issue by bkmeneguello** [ephread/inkgd#30]
`INK_CURRENT_VERSION` is [currently defined as 19]( https://github.com/ephread/inkgd/blob/3127d994106fa00e93430a9153f1b2fa3cc287ae/addons/inkgd/runtime/story.gd#L14) but ink's `inkVersionCurrent` [is 20](https://github.com/inkle/ink/blob/v1.0.0/ink-engine-runtime/Story.cs#L19)

**Comment by ephread** [comment]
Hey @bkmeneguello inkgd doesn't support stories compiled with inklecate 1.0.0 yet. I'll update the version once I port over all the changes!

**Comment by bkmeneguello** [comment]
I'm using this version without problems (yet), I can even run "The Intercept" compiled by Inklecate 1.0.0 with all flows. I didn't tested newer features yet.

**Comment by videlanicolas** [comment]
I think we need to bump this version to 20. While doing some test runs of Inkgd I'm getting this same error.

I'd say we bump the version, and if there are incompatibilities between Ink and Inkgd they should be filed as bugs.

**Comment by ephread** [comment]
> I'd say we bump the version, and if there are incompatibilities between Ink and Inkgd they should be filed as bugs.

I'm not keen on doing this because it sounds like a maintenance nightmare down the line.

Fortunately, the migration to 1.0.0 is nearly completed. I just have to dig into the codebase and find why 2 tests are crashing and 4 tests are not passing. I should be able to release the next version over the weekend or early next week.

**Comment by ephread** [comment]
Fixed by #28.
